ExamManagement/Controllers/ExamController.cs
using ExamManagement.Entities;
using ExamManagement.Filters;
using ExamManagement.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExamManagement.Controllers
{
    [SessionAuthorize]
    public class ExamController : Controller
    {
        private readonly IExamRepository _examRepository;
        private readonly ISubjectRepository _subjectRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly IExamAuditLogRepository _examAuditLogRepository;
        public ExamController(IExamRepository examRepository, IStudentRepository studentRepository, ISubjectRepository subjectRepository, IExamAuditLogRepository examAuditLogRepository)
        {
            _examRepository = examRepository;
            _subjectRepository = subjectRepository;
            _studentRepository = studentRepository;
            _examAuditLogRepository = examAuditLogRepository;
        }
        public async Task<IActionResult> Index()
        {
            var exams = await _examRepository.GetAllAsync();
            return View(exams);
        }

        public async Task<IActionResult> Create()
        {
            ViewData["StudentId"] = new SelectList(await _studentRepository.GetAllAsync(), "StudentId", "FirstName", "LastName");
            ViewData["SubjectCode"] = new SelectList(await _subjectRepository.GetAllAsync(), "SubjectCode", "SubjectName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Exam exam)
        {
            ViewData["StudentId"] = new SelectList(await _studentRepository.GetAllAsync(), "StudentId", "FirstName", "LastName");
            ViewData["SubjectCode"] = new SelectList(await _subjectRepository.GetAllAsync(), "SubjectCode", "SubjectName");
            if (!ModelState.IsValid) 
                return View(exam);
            var dbExam = await _examRepository.GetByCompositeKeyAsync(null, exam.SubjectCode, exam.StudentId, exam.ExamDate);
            if (dbExam != null)
            {
                ModelState.AddModelError("ExamDate", "The same student should not be given an exam more than once on the same date for the same subject.");
                return View(exam);
            }
            if ((await _studentRepository.GetByIdAsync(exam.StudentId))!.ClassLevel != (await _subjectRepository.GetByIdAsync(exam.SubjectCode))!.ClassLevel)
            {
                ModelState.AddModelError("StudentId", "The student's class level must match the class level of the subject.");
                ModelState.AddModelError("SubjectCode", "The subject's class level must match the class level of the student.");
                return View(exam);
            }

            await _examRepository.AddAsync(exam);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["StudentId"] = new SelectList(await _studentRepository.GetAllAsync(), "StudentId", "FirstName", "LastName");
            ViewData["SubjectCode"] = new SelectList(await _subjectRepository.GetAllAsync(), "SubjectCode", "SubjectName");
            var exam = await _examRepository.GetByIdAsync(id);
            if (exam == null)
                return NotFound();
            return View(exam);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Exam exam)
        {
            ViewData["StudentId"] = new SelectList(await _studentRepository.GetAllAsync(), "StudentId", "FirstName", "LastName");
            ViewData["SubjectCode"] = new SelectList(await _subjectRepository.GetAllAsync(), "SubjectCode", "SubjectName");
            if (!ModelState.IsValid)
                return View(exam);
            var dbExam = await _examRepository.GetByCompositeKeyAsync(exam.ExamId, exam.SubjectCode, exam.StudentId, exam.ExamDate);
            if (dbExam != null)
            {
                ModelState.AddModelError("ExamDate", "The same student should not be given an exam more than once on the same date for the same subject.");
                return View(exam);
            }
            if ((await _studentRepository.GetByIdAsync(exam.StudentId))!.ClassLevel != (await _subjectRepository.GetByIdAsync(exam.SubjectCode))!.ClassLevel)
            {
                ModelState.AddModelError("StudentId", "The student's class level must match the class level of the subject.");
                ModelState.AddModelError("SubjectCode", "The subject's class level must match the class level of the student.");
                return View(exam);
            }

            var oldGrade = (await _examRepository.GetByIdAsync(exam.ExamId))!.Grade;
            await _examRepository.UpdateAsync(exam);
            await _examAuditLogRepository.AddAsync(new() { OldGrade = oldGrade, NewGrade = exam.Grade, ChangedAt = DateTime.Now, ExamId = exam.ExamId, ChangedBy = HttpContext.Session.GetString("Username")! });
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var exam = await _examRepository.GetByIdAsync(id);
            if (exam == null)
                return NotFound();

            return View(exam);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _examRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ExamManagement/Controllers/ExamLogController.cs
using ExamManagement.Filters;
using ExamManagement.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExamManagement.Controllers
{
    [SessionAuthorize]
    public class ExamLogController : Controller
    {
        private readonly IExamAuditLogRepository _examAuditLogRepository;
        private readonly IExamRepository _examRepository;
        public ExamLogController(IExamAuditLogRepository examAuditLogRepository, IExamRepository examRepository)
        {
            _examAuditLogRepository = examAuditLogRepository;
            _examRepository = examRepository;
        }
        public async Task<IActionResult> Index(int? examId = null)
        {
            ViewData["ExamId"] = new SelectList(await _examRepository.GetAllAsync(), "ExamId", "ExamId");
            var examLogs = await _examAuditLogRepository.GetAllAsync(examId);
            return View(examLogs);
        }
    }
}

ExamManagement/Controllers/StudentController.cs
using ExamManagement.Entities;
using ExamManagement.Filters;
using ExamManagement.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ExamManagement.Controllers
{
    [SessionAuthorize]
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;

        public StudentController(IStudentRepository studentRepository)
        {
            _studentRepository = studentRepository;
        }

        public async Task<IActionResult> Index()
        {
            var students = await _studentRepository.GetAllAsync();
            return View(students);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(Student student)
        {
            if (!ModelState.IsValid)
                return View(student);

            await _studentRepository.AddAsync(student);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var student = await _studentRepository.GetByIdAsync(id);
            if (student == null)
                return NotFound();

            return View(student);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Student student)
        {
            if (!ModelState.IsValid)
                return View(student);

            await _studentRepository.UpdateAsync(student);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var student = await _studentRepository.GetByIdAsync(id);
            if (student == null)
                return NotFound();

            return View(student);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _studentRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ExamManagement/Controllers/SubjectController.cs
using ExamManagement.Entities;
using ExamManagement.Filters;
using ExamManagement.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ExamManagement.Controllers
{
    [SessionAuthorize]
    public class SubjectController : Controller
    {
        private readonly ISubjectRepository _subjectRepository;
        public SubjectController(ISubjectRepository subjectRepository)
        {
            _subjectRepository = subjectRepository;
        }
        public async Task<IActionResult> Index()
        {
            var subjects = await _subjectRepository.GetAllAsync();
            return View(subjects);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(Subject subject)
        {
            if (!ModelState.IsValid)
                return View(subject);

            await _subjectRepository.AddAsync(subject);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(string code)
        {
            var subject = await _subjectRepository.GetByIdAsync(code);
            if (subject == null)
                return NotFound();

            return View(subject);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Subject subject)
        {
            if (!ModelState.IsValid)
                return View(subject);

            await _subjectRepository.UpdateAsync(subject);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string code)
        {
            var subject = await _subjectRepository.GetByIdAsync(code);
            if (subject == null)
                return NotFound();

            return View(subject);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string code)
        {
            await _subjectRepository.DeleteAsync(code);
            return RedirectToAction(nameof(Index));
        }
    }
}

ExamManagement/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Exam Management</title>
    <style>
        body{
            background-color: rgb(196, 197, 197);
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
</body>
</html>

ExamManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Exam Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Subject" asp-action="Index">Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Exam" asp-action="Index">Exams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="ExamLog" asp-action="Index">ExamAuditLogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
</body>
</html>